-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpIZp/O/h5h7nRfTP
UE/ThgFyWd3QVcCCOxLmbr4qNe+gCgYIKoZIzj0DAQehRANCAARD2L2qy+eydTyo
Lzg5YKKmco1cxHrKGXSPB4qPqMuza3Sv7fWBD4GIwqNyZWF3laywz408No+1WrKh
n9KirmIa
-----END PRIVATE KEY-----